import { FormEvent, useEffect, useRef, useState } from 'react';
import { Building2, FolderTree, Plus, Users, X } from 'lucide-react';
import { Branch, Category, Cost, MasterData, masterDataRepository, Staff } from './master-data';

const roleLabel: Record<Staff['role'], string> = { MANAGER: 'ผู้จัดการ', CASHIER: 'แคชเชียร์' };

/** Master-data UI backed by JSON today and the MasterDataRepository API contract tomorrow. */
export function SetupPreview({ close }: { close: () => void }) {
  const dialog = useRef<HTMLDialogElement>(null);
  const [data, setData] = useState<MasterData>();
  const [error, setError] = useState('');
  useEffect(() => { const element = dialog.current; element?.showModal(); void load(); return () => element?.close(); }, []);
  async function load() { try { setData(await masterDataRepository.list()); } catch { setError('โหลดข้อมูลตั้งต้นไม่สำเร็จ'); } }
  async function addCategory(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const name = String(new FormData(event.currentTarget).get('category') ?? '').trim(); if (!name) return; await masterDataRepository.createCategory({ name }); event.currentTarget.reset(); await load(); }
  async function addBranch(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); const name = String(values.get('branch') ?? '').trim(); if (!name) return; await masterDataRepository.createBranch({ name, address: String(values.get('address') ?? '').trim() }); event.currentTarget.reset(); await load(); }
  async function addStaff(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); const name = String(values.get('staff') ?? '').trim(); const branchId = String(values.get('branch') ?? ''); if (!name || !branchId) return; await masterDataRepository.createStaff({ name, role: values.get('role') === 'MANAGER' ? 'MANAGER' : 'CASHIER', branchIds: [branchId] }); event.currentTarget.reset(); await load(); }
  async function addCost(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); const productName = String(values.get('product') ?? '').trim(); const amount = Number(values.get('cost')); if (!productName || !Number.isFinite(amount) || amount < 0) return; await masterDataRepository.createCost({ productName, amount: amount.toFixed(2) }); event.currentTarget.reset(); await load(); }
  const branchName = (id: string) => data?.branches.find(branch => branch.id === id)?.name ?? 'ไม่ระบุสาขา';
  return <dialog ref={dialog} className="modal setup-preview" aria-labelledby="setup-preview-title" onCancel={event => { event.preventDefault(); close(); }}>
    <div className="section-heading"><div><span className="eyebrow green">MASTER DATA · JSON SEED</span><h2 id="setup-preview-title">ข้อมูลตั้งต้นร้าน</h2></div><button className="icon-button" onClick={close} aria-label="ปิด"><X /></button></div>
    <p className="muted">ข้อมูลในหน้านี้มาจาก JSON และเรียกผ่าน repository contract เพื่อเตรียมเปลี่ยนเป็น API/DB ภายหลัง</p>{error && <p className="error">{error}</p>}
    {!data ? <p role="status">กำลังโหลดข้อมูลตั้งต้น…</p> : <><section className="setup-section"><h3><FolderTree size={18} />หมวดหมู่สินค้า</h3><div className="chip-list">{data.categories.map((item: Category) => <span className="chip" key={item.id}>{item.name}<small>{item.products} สินค้า</small></span>)}</div><form className="inline-form" onSubmit={addCategory}><input name="category" maxLength={80} placeholder="เช่น ของใช้" /><button className="secondary"><Plus size={15} />เพิ่มหมวดหมู่</button></form></section>
    <section className="setup-section"><h3>ต้นทุนสินค้า</h3><div className="setup-list">{data.costs.map((item: Cost) => <div key={item.id}><strong>{item.productName}</strong><small>ต้นทุนล่าสุด</small><span className="cost">฿{item.amount}</span></div>)}</div><form className="inline-form two-fields" onSubmit={addCost}><input name="product" maxLength={200} placeholder="ชื่อสินค้า" /><input name="cost" type="number" min="0" step="0.01" placeholder="ต้นทุน" /><button className="secondary"><Plus size={15} />บันทึกต้นทุน</button></form></section>
    <section className="setup-section"><h3><Building2 size={18} />สาขา</h3><div className="setup-list">{data.branches.map((item: Branch) => <div key={item.id}><strong>{item.name}</strong><small>{item.address}</small><span className={`status ${item.status === 'SETUP' ? 'inactive' : ''}`}>{item.status === 'ACTIVE' ? 'เปิดใช้งาน' : 'กำลังตั้งค่า'}</span></div>)}</div><form className="inline-form two-fields" onSubmit={addBranch}><input name="branch" maxLength={120} placeholder="ชื่อสาขา" /><input name="address" maxLength={200} placeholder="ที่อยู่ (ไม่บังคับ)" /><button className="secondary"><Plus size={15} />เพิ่มสาขา</button></form></section>
    <section className="setup-section"><h3><Users size={18} />พนักงาน</h3><div className="setup-list">{data.staff.map((item: Staff) => <div key={item.id}><strong>{item.name}</strong><small>{roleLabel[item.role]} · {item.branchIds.map(branchName).join(', ')}</small></div>)}</div><form className="inline-form two-fields" onSubmit={addStaff}><input name="staff" maxLength={100} placeholder="ชื่อพนักงาน" /><select name="role" aria-label="บทบาท"><option value="CASHIER">แคชเชียร์</option><option value="MANAGER">ผู้จัดการ</option></select><select name="branch" aria-label="สาขา">{data.branches.map(branch => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select><button className="secondary"><Plus size={15} />เพิ่มพนักงาน</button></form></section></>}
  </dialog>;
}
